vich_uploader:
    db_driver: orm

    mappings:
        article_images:
            uri_prefix: '%article_images%'
            upload_destination: '%kernel.project_dir%/public%article_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer